# sweep_config.yaml
program: sweep.py
name: Hyperbolic
method: grid
metric:
  goal: minimize
  name: valid_n_step_rollout_rmse  #valid_n_step_rollout_pos_rmse 
parameters:
  model:
    values: ['gnn']
  seed:
    values: [42]
  mp_steps:
    values: [1, 2, 4, 8, 10, 12, 14, 16, 20, 24]  # Number of hidden layers to test  [3, 6, 8, 10, 12, 16, 24]
  layers:
    values: [2]  # Number of hidden layers to test
  hidden:
    values: [128]  # Hidden dimensions to test
  ratio:
    values: [1.]  # Noise levels to test
  noise:
    values: [0.01]  # Noise levels to test
  batch_size:
    values: [8]  # Batch sizes to test
  lr:
    values: [0.001]  # Learning rates to test
  epochs:
    values: [250]  # Epochs to test
  input_size:
    value: 1
  output_size:
    value: 1
  shared_mp:
    values: [True]
  plots_flag:
    values: [True]
  plot_worst:
    values: [False]
  eval_freq:
    values: [5]
